library(rio)
library(tidyverse)
library(broom.mixed)
library(brms)
library(flexmix)
library(grid)
library(ggridges)
library(patchwork)
# Install odin2 and dust2 using:
# install.packages(
#   c("odin2", "dust2"),
#   repos = c("https://mrc-ide.r-universe.dev", "https://cloud.r-project.org"))
library(odin2)
library(dust2)
library(ggpmisc)
source("R/function_data_cleaning.R")
source("R/function_clean_pop_data.R")
source("R/function_simulated_pop.R")
source("R/function_process_regression_outputs.R")
source("R/function_figures.R")
source("R/function_run_seir_model.R")
source("R/function_seir_model.R")
